http:
  port: 8080
  corsEnabled: true
  profilingEnabled: true


database:
  connectionString: "postgres://postgres:postgres@localhost:5432/sample-project?sslmode=disable"


  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "raytran"
  password: "password"
  dbName: "sample-project"
  migrationsPath: "migrations"
  connectionMaxLifetimeMs: 540000
  maxIdleConnections: 10
  maxOpenConnections: 50
  debug: false


secret:
  pepper: "pepper"

#Postgres
#  APP_ENV=local
#  API_PORT=8888
#  DB_HOST=127.0.0.1
#  DB_DRIVER=postgres
#  ACCESS_SECRET=98hbun98h
#  REFRESH_SECRET=786dfdbjhsb
#  DB_USER=steven
#  DB_PASSWORD=password
#  DB_NAME=food-app
#  DB_PORT=5432